from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import json
import os
import platform
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


SCHEMA_VERSION = 1
PRODUCT = "Insta360_HW"
SUITE = "scripts/verify_all.ps1"
RELEASE_METADATA = {"VERSION", "REVISION", "UPDATE_NOTICE.json"}
EXCLUDED_PREFIXES = (".omc/", "docs/")


def _run(root: Path, *args: str) -> str:
    completed = subprocess.run(
        args,
        cwd=root,
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    return completed.stdout.strip()


def _included(relative: str) -> bool:
    normalized = relative.replace("\\", "/")
    while normalized.startswith("./"):
        normalized = normalized[2:]
    if not normalized or normalized in RELEASE_METADATA:
        return False
    if normalized.startswith(EXCLUDED_PREFIXES):
        return False
    # app/frontend is generated by the verified frontend source build. Keep the
    # hand-maintained waiting page in scope, but do not invalidate evidence when
    # hashed production assets are refreshed or release metadata is updated.
    if normalized.startswith("app/frontend/") and normalized != "app/frontend/waiting.html":
        return False
    return True


def source_files(root: Path) -> list[Path]:
    output = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z"],
        cwd=root,
        check=True,
        capture_output=True,
    ).stdout
    names = output.decode("utf-8", errors="surrogateescape").split("\0")
    return [root / name for name in sorted(set(names)) if _included(name)]


def source_fingerprint(root: Path) -> tuple[str, int]:
    digest = hashlib.sha256()
    files = source_files(root)
    for path in files:
        relative = path.relative_to(root).as_posix().encode("utf-8", errors="surrogateescape")
        digest.update(len(relative).to_bytes(4, "big"))
        digest.update(relative)
        if not path.is_file():
            digest.update(b"\0missing\0")
            continue
        content_digest = hashlib.sha256(path.read_bytes()).digest()
        digest.update(content_digest)
    return digest.hexdigest(), len(files)


def environment_fingerprint() -> dict[str, str]:
    try:
        pytest_version = importlib.metadata.version("pytest")
    except importlib.metadata.PackageNotFoundError:
        pytest_version = "missing"
    try:
        node_version = subprocess.run(
            ["node", "--version"],
            check=True,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
        ).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        node_version = "missing"
    return {
        "machine": platform.node(),
        "os": platform.platform(),
        "architecture": platform.machine(),
        "python": platform.python_version(),
        "pytest": pytest_version,
        "node": node_version,
    }


def receipt_path(receipt_dir: Path, fingerprint: str) -> Path:
    return receipt_dir / f"{fingerprint}.json"


def create_receipt(root: Path, receipt_dir: Path, revision: str = "") -> Path:
    root = root.resolve()
    head = _run(root, "git", "rev-parse", "HEAD").lower()
    if revision and head != revision.lower():
        raise ValueError(f"HEAD {head} does not match expected revision {revision.lower()}")
    fingerprint, file_count = source_fingerprint(root)
    receipt_dir.mkdir(parents=True, exist_ok=True)
    target = receipt_path(receipt_dir, fingerprint)
    value = {
        "schema": SCHEMA_VERSION,
        "product": PRODUCT,
        "suite": SUITE,
        "result": "passed",
        "source_fingerprint": fingerprint,
        "source_file_count": file_count,
        "verified_revision": head,
        "verified_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "environment": environment_fingerprint(),
    }
    temporary = target.with_name(f"{target.name}.{os.getpid()}.tmp")
    temporary.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    os.replace(temporary, target)
    return target


def verify_receipt(root: Path, receipt_dir: Path) -> tuple[bool, str]:
    root = root.resolve()
    fingerprint, file_count = source_fingerprint(root)
    target = receipt_path(receipt_dir, fingerprint)
    if not target.is_file():
        return False, f"no verification receipt for source fingerprint {fingerprint[:12]}"
    try:
        value = json.loads(target.read_text(encoding="utf-8-sig"))
    except (OSError, json.JSONDecodeError) as exc:
        return False, f"verification receipt is unreadable: {exc}"
    if not isinstance(value, dict):
        return False, "verification receipt root is not an object"
    expected = {
        "schema": SCHEMA_VERSION,
        "product": PRODUCT,
        "suite": SUITE,
        "result": "passed",
        "source_fingerprint": fingerprint,
        "source_file_count": file_count,
        "environment": environment_fingerprint(),
    }
    for key, expected_value in expected.items():
        if value.get(key) != expected_value:
            return False, f"verification receipt field {key} does not match this source or environment"
    return True, (
        f"verified source {fingerprint[:12]} at {value.get('verified_at', 'unknown time')} "
        f"from revision {str(value.get('verified_revision', ''))[:12]}"
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Create or validate source verification receipts.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    for command in ("create", "verify"):
        child = subparsers.add_parser(command)
        child.add_argument("--root", required=True, type=Path)
        child.add_argument("--receipt-dir", required=True, type=Path)
        if command == "create":
            child.add_argument("--revision", default="")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        if args.command == "create":
            target = create_receipt(args.root, args.receipt_dir, args.revision)
            print(f"Verification receipt saved: {target}")
            return 0
        valid, reason = verify_receipt(args.root, args.receipt_dir)
        print(reason)
        return 0 if valid else 2
    except (OSError, ValueError, subprocess.SubprocessError) as exc:
        print(f"Verification receipt error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
