from __future__ import annotations

CAPTURE_VISIBLE_PROPERTIES = [
    "Color",
    "Designator",
    "Graphic",
    "ID",
    "Implementation",
    "Implementation Path",
    "Implementation Type",
    "Location X-Coordinate",
    "Location Y-Coordinate",
    "Name",
    "Part Number",
    "Part Reference",
    "Part Type",
    "PCB Footprint",
    "PCB封装",
    "Power Pins Visible",
    "Primitive",
    "Reference",
    "Source Library",
    "Source Package",
    "Source Part",
    "SPLIT_INST",
    "SWAP_INFO",
    "Value",
    "等级",
    "规格型号",
    "器件描述（新整理）",
    "物料名称",
]

PLM_TEMPLATE_HEADERS = [
    "父项编码",
    "描述",
    "子项编码",
    "名称",
    "型号",
    "描述",
    "单位",
    "数量",
    "位号",
    "备注",
    "物料优选等级",
    "物料优选等级备注",
    "替代组编码",
    "替代策略",
    "替代方式",
    "替代优先级",
    "发料方式",
    "是否参与MRP运算",
    "是否跳层",
]

BOM_OPTIONAL_FIELDS = [
    "unit",
    "remark",
    "grade_remark",
    "alt_group",
    "alt_strategy",
    "alt_method",
    "alt_priority",
    "issue_method",
    "mrp",
    "jump_level",
]

FIELD_DEFAULTS = {
    "unit": "ea",
    "remark": "",
    "grade_remark": "",
    "alt_group": "",
    "alt_strategy": "",
    "alt_method": "",
    "alt_priority": "",
    "issue_method": "直接发料",
    "mrp": "是",
    "jump_level": "否",
}

